version: "3"
services:
  slugg:
    build: .
    ports:
      - 8000:8000
    networks:
      - redis
      - server_webgateway
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host: slu.gg"
      traefik.docker.network: "server_webgateway"
    restart: unless-stopped

  redis:
    image: redis:alpine
    networks:
      - redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./data:/data
    restart: unless-stopped
    

networks:
  redis:
    driver: bridge
  server_webgateway:
    external: true
