version: "3"
services:
  redis:
    image: redis:alpine
    networks:
      - redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./data:/data
    
  slugg:
    build: .
    ports:
      - 8000:8000
    networks:
      - redis

networks:
  redis:
    driver: bridge
